# This is a query for the Star Wars API
query Query {
  allFilms {
    films {
      title # I want to get the title of the film
      director
      releaseDate
      speciesConnection {
        species {
          name
          classification
          homeworld {
            name
          }
        }
      }
    }
  }
}
