name: Benchmark
on:
  workflow_call:
env:
  GO111MODULE: "on"
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg
          key: ${{ runner.os }}-go-pkg-${{ hashFiles('**/go.mod') }}
      - uses: actions/cache@v4
        with:
          path: ~/go/bin/benchstat
          key: ${{ runner.os }}-benchstat
      - uses: actions/cache@v4
        with:
          path: |
            bench-master.txt
          key: ${{ runner.os }}-bench-master
      - name: Benchmark
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
        run: |
          if ! command -v benchstat &> /dev/null
          then
              go get golang.org/x/perf/cmd/benchstat
              go install golang.org/x/perf/cmd/benchstat
          fi
          go test -run=XXX -bench=. -count=10  ./... >bench-$BRANCH.txt
          benchstat bench-master.txt bench-$BRANCH.txt >benchstat.txt
      - name: Comment benchmark results
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const data = fs.readFileSync('benchstat.txt', 'utf8');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: '```' + data + '```'
            });
