name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  test:
    uses: ./test.yml
    secrets: inherit
  benchmark:
    uses: ./benchmark.yml
    secrets: inherit
    needs: [test]
